### PR TITLE
Fixed size for each card in the 2d classification

### LINKED ISSUE #47: Set a fixed number of classes in 2d classification panel
Currently the number of items per row is variable and will depend on the number of classes.

image

A fixed number will make that the images have got always the same size independently of the number of classes

### PR DESCRIPTION
**Pull request by antolinos**
It keeps the same size for each card:
image

Previous version was:
image

### CODE REVIEW

File: src/legacy/pages/em/classification/sessionclassificationpage.tsx [hunk 1]
```diff
@@ -85,6 +85,8 @@ export default function SessionClassificationPage() {
                         .sort((a: Classification, b: Classification) => {
                           return b.classDistribution - a.classDistribution;
                         })
+
```
Comment (mgaonach) [inline src/legacy/pages/em/classification/sessionclassificationpage.tsx:88]: Setting a responsive colum size would avoid having to do this. Something like `<Col key={i} xs={12} sm={6} lg={4} xl={3} xxl={2}>`  seems to render well in all sizes.
Otherwise, setting `<Col key={i} xs={'auto'}>` will make the classes always appear as small as they can be, which is very similar to what happens when adding many empty columns.

Comment (mgaonach) [reply src/legacy/pages/em/classification/sessionclassificationpage.tsx]: Note, the `margin: 2` property will mess with bootstrap because it will make the column's element take more space than expected. To increase the spacing, it is better to set a `padding` value (bootstrap already sets one, so there already is spacing by default, but you can make it larger or smaller)

**Review by mgaonach — APPROVED** [review]
